kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: postgres-data
    fsType: ext4